### ISSUE TITLE
Difference of two imu parameters?

### ISSUE THREAD

**Issue by xukuanHIT** [ethz-asl/maplab#39]
Hi, I just want to know why there have two imu parameters files for euroc dataset? They have different meaning?

**Comment by dymczykm** [comment]
Hi @xukuanHIT,

right now, in the ``master`` branch, we have separate sets of parameters:
1. One for ROVIO/ROVIOLI, i.e. the visual-inertial odometry estimator.
2. One for maplab console, used for offline algorithms (mostly ``optvi`` command, so our visual-inertial least squares optimization).

In the upcoming update of maplab, these paremeter sets will get unified.

**Comment by xukuanHIT** [comment]
@dymczykm 
Thank you for reply.  I can get one set of parameters from user manual of imu now. How can I get the another? What is the relation between them?

**Comment by pxlong** [comment]
I have the same issue. How to decide the imu parameters in imu_parameter_maplab and imu_parameters_rovio?

**Comment by mfehr** [comment]
Hi @xukuanHIT @pxlong, basically the two sets of parameters originated from ROVIO and maplab using two different conventions for the IMU parameters. We have unified them in our upcoming release of maplab. You can simply try to do what we did there:

 * take the square of the maplab values for ROVIO.

ROVIO is using the variance, i.e. the square of the standard deviation (which is what maplab is using). However, if you look at the values we provided for the VI-Sensor, you'll notice that that doesn't really hold there, because values for the VI-Sensor have been tuned independently for maplab and ROVIO by different people in our lab to a point where they were satisfied with the performance of the estimator. The point being that you should start with the square of the maplab values, but if it doesn't work well you will probably need to tune them a bit yourselves.
